@startuml
hide circle

entity "Genomic Island" as gi {
    id : int <<generated>>
    --
    name : text !null unique
    type : text
    role : text
}

entity "Sequence" as seq {
    id : int <<generated>>
    --
    gi : int !null <<FK>>
    gbuid : text unique
    gc : float
    path : text !null unique
}

entity "Source" as src {
    id : int <<generated>>
    --
    gi : int !null <<FK>>
    strain : int !null <<FK>>
    start : int
    end : int
    size : int
    seq : int <<FK>>
}

entity "Strain" as strain {
    id : int <<generated>>
    --
    gbuid : text unique
    name : text !null
}

entity "PubMed IDs" as pmid {
    --
    source : int !null <<FK>>
    pmid : text !null unique
}

entity "Publications" as pub {
		--
		source : int !null <<FK>>
		publication : text unique
}

seq::gi --> gi::id
src::seq --> seq::id
src::gi --> gi::id
src::strain --> strain::id
pmid::source --> src::id
pub::source --> src::id
@enduml